MERGE INTO employees e USING (SELECT 'alice.johnson@example.com' email FROM dual) s ON (e.email=s.email) WHEN NOT MATCHED THEN INSERT (first_name,last_name,email,phone_number,department,designation,joining_date,employment_status) VALUES ('Alice','Johnson',s.email,'+1 555 0101','Engineering','Software Engineer',DATE '2023-01-15','ACTIVE');
MERGE INTO employees e USING (SELECT 'bob.smith@example.com' email FROM dual) s ON (e.email=s.email) WHEN NOT MATCHED THEN INSERT (first_name,last_name,email,phone_number,department,designation,joining_date,employment_status) VALUES ('Bob','Smith',s.email,'+1 555 0102','Finance','Accountant',DATE '2022-06-01','ACTIVE');
MERGE INTO employees e USING (SELECT 'carol.davis@example.com' email FROM dual) s ON (e.email=s.email) WHEN NOT MATCHED THEN INSERT (first_name,last_name,email,phone_number,department,designation,joining_date,employment_status) VALUES ('Carol','Davis',s.email,'+1 555 0103','Human Resources','HR Manager',DATE '2021-09-20','ACTIVE');

MERGE INTO app_users u USING (SELECT 'admin@example.com' email FROM dual) s ON (u.email=s.email) WHEN NOT MATCHED THEN INSERT (name,email,password) VALUES ('Admin',s.email,'$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy');
MERGE INTO app_users u USING (SELECT 'manager@example.com' email FROM dual) s ON (u.email=s.email) WHEN NOT MATCHED THEN INSERT (name,email,password) VALUES ('Manager',s.email,'$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy');
MERGE INTO app_users u USING (SELECT 'viewer@example.com' email FROM dual) s ON (u.email=s.email) WHEN NOT MATCHED THEN INSERT (name,email,password) VALUES ('Viewer',s.email,'$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy');

MERGE INTO attendance_records a USING (SELECT id employee_id FROM employees WHERE email='alice.johnson@example.com') s ON (a.employee_id=s.employee_id AND a.attendance_date=DATE '2025-01-06') WHEN NOT MATCHED THEN INSERT (employee_id,attendance_date,attendance_status,check_in_time,check_out_time,total_working_hours,remarks) VALUES (s.employee_id,DATE '2025-01-06','PRESENT',TIMESTAMP '1970-01-01 09:00:00',TIMESTAMP '1970-01-01 17:30:00',8.50,'Regular day');
MERGE INTO attendance_records a USING (SELECT id employee_id FROM employees WHERE email='bob.smith@example.com') s ON (a.employee_id=s.employee_id AND a.attendance_date=DATE '2025-01-06') WHEN NOT MATCHED THEN INSERT (employee_id,attendance_date,attendance_status,check_in_time,check_out_time,total_working_hours,remarks) VALUES (s.employee_id,DATE '2025-01-06','HALF_DAY',TIMESTAMP '1970-01-01 09:15:00',TIMESTAMP '1970-01-01 13:15:00',4.00,'Medical appointment');
MERGE INTO attendance_records a USING (SELECT id employee_id FROM employees WHERE email='carol.davis@example.com') s ON (a.employee_id=s.employee_id AND a.attendance_date=DATE '2025-01-06') WHEN NOT MATCHED THEN INSERT (employee_id,attendance_date,attendance_status,check_in_time,check_out_time,total_working_hours,remarks) VALUES (s.employee_id,DATE '2025-01-06','ABSENT',NULL,NULL,0.00,'Approved leave');
